[package]
name = "simple_graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.9.0"
rand = "0.8.5"
rand_distr = "0.4.3"
winit = "0.27.4"
