name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Rust cache
      uses: Swatinem/rust-cache@v2.2.0
      
    - name: Install package
      if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
      uses: ConorMacBride/install-package@v1.1.0 
      with:
        apt: libfontconfig-dev
        

    - uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=${{ matrix.target }}
